[package]
authors = ["tatamiya <tamyuji1002@gmail.com>"]
edition = "2018"
name = "errors"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
derive_more = "0"
env_logger = "0.8"
log = "0.4"
