[package]
authors = ["tatamiya <tamyuji1002@gmail.com>"]
edition = "2018"
name = "middleware"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-service = "2"
actix-web = "3"
futures = "0"
